source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WiLibrary_Example', :exclusive => true do
  pod "WiLibrary", :path => "../"
end

target 'WiLibrary_Tests', :exclusive => true do
  pod "WiLibrary", :path => "../"

  
end
